ourside/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^', include('qanda.urls'))
]

qanda/urls.py
from django.conf.urls import url

from . import views

app_name = 'qanda'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^post/$', views.PostQuestionView.as_view(), name='post'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^user/(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name='profile')
]

qanda/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class Profile(models.Model):
    """This extends a user through a 1-1 field, adding a faculty and role"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    """The One to One reference to the user"""
    faculty = models.CharField(max_length=len("Florence Nightingale Faculty of Nursing, Midwifery & Paliative Care"), blank=True)
    """The faculty the User is in"""
    role = models.CharField(max_length=20, blank=True)
    """The role of the User"""


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    """This creates a profile when a user is created"""
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Question(models.Model):
    """This is a question on the q&a site"""
    question_title = models.CharField(max_length=200)
    """The title of the question"""
    question_body = models.TextField()
    """The body of the question"""
    pub_date = models.DateTimeField(default=timezone.now)
    """The publication date of the question, default is the current date & time"""
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, default=None, null=True)
    """The author of the Question"""

    def __str__(self):
        """
        Gets the string representation of the Question
        :return: the title of the question
        """
        return self.question_title


class Answer(models.Model):
    """This is an answer to a question"""
    answer_text = models.TextField()
    """The text of the answer"""
    pub_date = models.DateTimeField(default=timezone.now)
    """The publication date of the answer, default is the current date & time"""
    question_answered = models.ForeignKey(Question, on_delete=models.CASCADE)
    """The question this answer has answered"""
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, default=None, null=True)
    """The auther of the answer"""

    def __str__(self):
        """
        Gets the string representation of the Answer
        :return: Answer to <question_answered.question_title> published <pub_date>
        """
        return "Answer to " + self.question_answered.question_title + " published " + str(self.pub_date)

qanda/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import re

from django.core.exceptions import ValidationError

from qanda.models import Question, Answer


class SignUpForm(UserCreationForm):
    """This is the form used to create a new user"""
    first_name = forms.CharField(max_length=30, label="First Name")
    """The first name of the user"""
    last_name = forms.CharField(max_length=30, label="Last Name")
    """The last name of the user"""
    email = forms.EmailField(max_length=254, label="Email Address", help_text='Required. Inform a valid email address.')
    """The email address of the user (must end in kcl.ac.uk)"""
    role = forms.ChoiceField(choices=[(x,x) for x in ("Undergraduate", "Postgraduate", "Staff", "Other")], label="Role")
    """The role of the user"""
    faculty = forms.ChoiceField(
        choices=[(x, x) for x in ("Faculty of Arts & Humanities",
         "King's Business School",
         "Dental Institute",
         "Institute of Psychiatry, Psychology & Neuroscience",
         "Faculty of Life Sciences & Medicine",
         "The Dickson Poon School of Law",
         "Faculty of Natural & Mathematical Sciences",
         "Florence Nightingale Faculty of Nursing, Midwifery & Paliative Care",
         "Faculty of Social Science & Public Policy",
         "Other")],
        label="Faculty"
    )
    """The faculty of the user"""

    def clean_email(self):
        """
        Asserts the email is in the correct format
        :return: the email address
        :raises ValidationError: if the email address doesn't end in kcl.ac.uk
        """
        email = self.cleaned_data['email']
        if not re.match(r"(^[a-zA-Z0-9_.+-]+@kcl.ac.uk)", email):
            raise ValidationError("Please enter a KCL email address")
        return email

    class Meta:
        """The metadata for the Form"""
        model = User
        """The model the form creates"""
        fields = ('username', 'first_name', 'last_name', 'email', 'role', 'faculty', 'password1', 'password2')
        """The fields in the form"""


class QuestionForm(forms.ModelForm):
    """This is the form used to post a question"""
    question_title = forms.CharField(max_length=200)
    """The title of the question"""
    question_body = forms.CharField(widget=forms.Textarea)
    """The body of the question"""

    class Meta:
        """The metadata for the form"""
        model = Question
        """The model the form creates"""
        fields = ('question_title', 'question_body')
        """The fields in the form"""


class AnswerForm(forms.ModelForm):
    """This is the form used to post an answer to a question"""
    answer_text = forms.CharField(widget=forms.Textarea, label=None)
    """The text of the answer"""

    class Meta:
        """The metadata for the form"""
        model = Answer
        """The model the form creates"""
        fields = ('answer_text',)
        """The fields in the form"""

qanda/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import reverse
from django.utils import timezone

# Create your views here.
from django.views import generic
from django.views.generic.edit import FormMixin

from qanda.forms import SignUpForm, QuestionForm, AnswerForm
from qanda.forms import SignUpForm, AnswerForm
from .models import Question, Profile, Answer


class IndexView(generic.ListView):
    template_name = "qanda/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(FormMixin, generic.DetailView):
    model = Question
    template_name = "qanda/detail.html"
    form_class = AnswerForm

    def get_success_url(self):
        return reverse('qanda:detail', kwargs={'pk': self.get_object().pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form_class()()
        return context

    def form_valid(self, form):
        question_answered = self.get_object()
        author = self.request.user.profile
        text = form.cleaned_data['answer_text']
        a = Answer(author=author, question_answered=question_answered, answer_text=text)
        a.save()
        return super().form_valid(form)


class ProfileView(generic.DetailView):
    model = Profile
    template_name = "qanda/profile.html"


class PostQuestionView(generic.FormView):
    template_name = 'qanda/post.html'
    form_class = QuestionForm
    success_url = '/'

    def get_success_url(self):
        """The redirect if the creation was successful"""
        return reverse('qanda:detail', args=(self.object.id,))

    def post(self, request, *args, **kwargs):
        """Handles the post method, returns 403 if not logged in"""
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        """
        If the form is valid
        :param form: the form
        :return: The HttpResponse
        """
        clean_data = form.cleaned_data
        text = clean_data['question_body']
        title = clean_data['question_title']
        user = self.request.user.profile
        q = Question(question_title=title, question_body=text, author=user)
        q.save()
        self.object = q
        return super().form_valid(form)


def signup(request):
    """The signup view"""
    if request.method == 'POST':
        # if the method is post
        form = SignUpForm(request.POST)
        if form.is_valid():
            # if the form is valid, make a user
            user = form.save()
            user.refresh_from_db()
            user.profile.faculty = form.cleaned_data.get('faculty')
            user.profile.role = form.cleaned_data.get('role')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    # reshow the form if not valid, or not post
    return render(request, 'qanda/signup.html', {'form': form})

qanda/templates/qanda/detail.html
{% extends 'ourside/template.html' %}
{% block title %}{{ question.question_title }}{% endblock %}
{% block body %}
<h1>{{ question.question_title }}</h1>
<p>{{ question.question_text }}</p>
<p>posted by
            {% if question.author %}
                <a href="{% url 'qanda:profile' question.author_id %}">{{question.author.user.first_name}} {{ question.author.user.last_name }}</a>
            {% else %}
            &lt;removed&gt;
            {% endif %} on {{ question.pub_date }}</p>
<br />
<h2>Answers</h2>
<br />
{% for answer in question.answer_set.all %}
    <p>{{ answer.answer_text }}</p>
    <p>posted by
            {% if answer.author %}
                    <a href="{% url 'qanda:profile' answer.author_id %}">{{answer.author.user.first_name}} {{ answer.author.user.last_name }}</a>
            {% else %}
            &lt;removed&gt;
            {% endif %} on {{ answer.pub_date }}</p>
    <br />
{% endfor %}
    {% if user.is_authenticated %}
        <h2>Post an answer</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Post</button>
        </form>
    {% endif %}
{% endblock %}

qanda/templates/qanda/index.html
{% extends 'ourside/template.html' %}
{% block title %}KCL Q and A{% endblock %}
{% block body %}
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'qanda:detail' question.id %}">{{ question.question_title }}</a>
                posted by
                {% if question.author %}
                    <a href="{% url 'qanda:profile' question.author_id %}">{{question.author.user.first_name}} {{ question.author.user.last_name }}</a>
                {% else %}
                    &lt;removed&gt;
                {% endif %}
                on {{ question.pub_date }}

            </li>
        {% endfor %}
    </ul>

{% endif %}
{% endblock %}

qanda/templates/qanda/post.html
{% extends 'ourside/template.html' %}
{% block title %}Post a new question{% endblock %}
{% block body %}
    {% if user.is_authenticated %}
        <h2>Post a new question</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Post</button>
        </form>
    {% else %}
        <h2>You are not logged in!!!</h2>
    {% endif %}
{% endblock %}

qanda/templates/qanda/profile.html
{% extends 'ourside/template.html' %}
{% block title %}{{ profile.user.first_name }} {{ profile.user.last_name }}{% endblock %}
{% block body %}
    <h1>{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
    <h2>{{ profile.role }} from {{ profile.faculty }}</h2>
{% endblock %}

qanda/templates/qanda/signup.html
{% extends 'ourside/template.html' %}
{% block title %}Signup{% endblock %}
{% block body %}
  <h2>Sign up</h2>
  <form method="post" class="signup-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}